import RPi.GPIO as GPIO
import time # Set the GPIO mode to BCM
GPIO.setmode(GPIO.BCM) # Define LED pins
RLED1=7
BLED1=6
RLED2=5
BLED2=4
RLED3=27
BLED3=17
RLED4=1
BLED4=21

# Set LED pins as outputs
GPIO.setup(RLED1, GPIO.OUT)
GPIO.setup(BLED1, GPIO.OUT)
GPIO.setup(RLED2, GPIO.OUT)
GPIO.setup(BLED2, GPIO.OUT)
GPIO.setup(RLED3, GPIO.OUT)
GPIO.setup(BLED3, GPIO.OUT)
GPIO.setup(RLED4, GPIO.OUT)
GPIO.setup(BLED4, GPIO.OUT) # Pattern 1

def blink_pattern1():
    GPIO.output(RLED1, GPIO.HIGH)
    time.sleep(0.1)
    GPIO.output(RLED1, GPIO.LOW)
    GPIO.output(BLED1, GPIO.HIGH)
    time.sleep(0.1)
    GPIO.output(BLED1, GPIO.LOW)
    GPIO.output(RLED2, GPIO.HIGH)
    time.sleep(0.1)
    GPIO.output(RLED2, GPIO.LOW)
    GPIO.output(BLED2, GPIO.HIGH)
    time.sleep(0.1)
    GPIO.output(BLED2, GPIO.LOW)
    GPIO.output(RLED3, GPIO.HIGH)
    time.sleep(0.1)
    GPIO.output(RLED3, GPIO.LOW)
    GPIO.output(BLED3, GPIO.HIGH)
    time.sleep(0.1)
    GPIO.output(BLED3, GPIO.LOW)
    GPIO.output(RLED4, GPIO.HIGH)
    time.sleep(0.1)
    GPIO.output(RLED4, GPIO.LOW)
    GPIO.output(BLED4, GPIO.HIGH)
    time.sleep(0.1)
    GPIO.output(BLED4, GPIO.LOW)
    GPIO.output(BLED4, GPIO.HIGH)
    time.sleep(0.1)
    GPIO.output(BLED4, GPIO.LOW)
    GPIO.output(RLED4, GPIO.HIGH)
    time.sleep(0.1)
    GPIO.output(RLED4, GPIO.LOW)
    GPIO.output(BLED3, GPIO.HIGH)
    time.sleep(0.1)
    GPIO.output(BLED3, GPIO.LOW)
    GPIO.output(RLED3, GPIO.HIGH)
    time.sleep(0.1)
    GPIO.output(RLED3, GPIO.LOW)
    GPIO.output(BLED2, GPIO.HIGH)
    time.sleep(0.1)
    GPIO.output(BLED2, GPIO.LOW)
    GPIO.output(RLED2, GPIO.HIGH)
    time.sleep(0.1)
    GPIO.output(RLED2, GPIO.LOW)
    GPIO.output(BLED1, GPIO.HIGH)
    time.sleep(0.1)
    GPIO.output(BLED1, GPIO.LOW)
    GPIO.output(RLED1, GPIO.HIGH)
    time.sleep(0.1)
    GPIO.output(RLED1, GPIO.LOW)
    time.sleep(0.1)

def blink_pattern2():
    GPIO.output(RLED1, GPIO.HIGH)
    GPIO.output(RLED2, GPIO.HIGH)
    GPIO.output(RLED3, GPIO.HIGH)
    GPIO.output(RLED4, GPIO.HIGH)
    GPIO.output(BLED1, GPIO.LOW)
    GPIO.output(BLED2, GPIO.LOW)
    GPIO.output(BLED3, GPIO.LOW)
    GPIO.output(BLED4, GPIO.LOW)
    time.sleep(.5)
    GPIO.output(BLED1, GPIO.HIGH)
    GPIO.output(BLED2, GPIO.HIGH)
    GPIO.output(BLED3, GPIO.HIGH)
    GPIO.output(BLED4, GPIO.HIGH)
    GPIO.output(RLED1, GPIO.LOW)
    GPIO.output(RLED2, GPIO.LOW)
    GPIO.output(RLED3, GPIO.LOW)
    GPIO.output(RLED4, GPIO.LOW)
    time.sleep(.5)
    GPIO.output(BLED1, GPIO.LOW)
    GPIO.output(BLED2, GPIO.LOW)
    GPIO.output(BLED3, GPIO.LOW)
    GPIO.output(BLED4, GPIO.LOW)
    time.sleep(.5)

def blink_pattern3():
    GPIO.output(RLED1, GPIO.HIGH)
    GPIO.output(BLED4, GPIO.HIGH)
    time.sleep(.5)
    GPIO.output(RLED1, GPIO.LOW)
    GPIO.output(BLED4, GPIO.LOW)
    GPIO.output(BLED1, GPIO.HIGH)
    GPIO.output(RLED4, GPIO.HIGH)
    time.sleep(.5)
    GPIO.output(BLED1, GPIO.LOW)
    GPIO.output(RLED4, GPIO.LOW)
    GPIO.output(RLED2, GPIO.HIGH)
    GPIO.output(BLED3, GPIO.HIGH)
    time.sleep(.5)
    GPIO.output(RLED2, GPIO.LOW)
    GPIO.output(BLED3, GPIO.LOW)
    GPIO.output(RLED1, GPIO.HIGH)
    GPIO.output(BLED4, GPIO.HIGH)
    time.sleep(.5)
    GPIO.output(RLED1, GPIO.LOW)
    GPIO.output(BLED4, GPIO.LOW)
    GPIO.output(BLED2, GPIO.HIGH)
    GPIO.output(RLED3, GPIO.HIGH)
    time.sleep(.5)
    GPIO.output(BLED2, GPIO.LOW)
    GPIO.output(RLED3, GPIO.LOW)
    time.sleep(.5)
while True:
    blink_pattern1()
    blink_pattern2()
    blink_pattern2()
    blink_pattern3()
